#!/bin/bash

# THIS IS A AUTOMATION SCRIPT THAT AUTOMATES LINUX UPDATING PROCESS

# Color Variable
TEXT_RESET='\e[0m'
TEXT_YELLOW='\e[0;33m'
TEXT_RED_B='\e[1;31m'

echo ""
echo ""
echo -e "\e[1;33m       Hello $USER, lets update this system. \e[0m"
echo ""
sudo apt update -y;
echo ""
echo -e "\e[1;33m       Repositories Updated Successfully. \e[0m"
echo ""
sudo apt upgrade -y;
echo ""
echo -e "\e[1;33m       Programs and Apps Updated Successfully. \e[0m"
echo ""
sudo apt dist-upgrade -y;
sudo apt full-upgrade -y;
echo ""
echo -e "\e[1;33m       Distro Updated Successfully. \e[0m"
echo ""


# Flatpak Update

if [[ $(which flatpak) == /usr/bin/flatpak  ]]
then
        sudo flatpak update -y;
        echo ""
        echo -e "\e[1;33m       Flatpak Apps Updated Successfully. \e[0m"
        echo ""
        sudo flatpak uninstall --unused -y;
fi;


# House keeping

sudo apt autoremove -y;
sudo apt autoclean -y;
sudo updatedb;
echo ""
echo ""
echo -e "\e[1;33m       Removed All Unused Libraries Successfully. \e[0m"
echo ""
echo -e "\e[1;33m                  UPDATE DONE !!! \e[0m"
echo ""


# notes

echo ""
echo -e "\e[1;31m       Process took $SECONDS seconds to finish... \e[0m"
echo "
"


# reboot prompt

if [ -f /var/run/reboot-required ]; then
    echo -e $TEXT_RED_B
    echo '	Reboot required!	'
    echo -e $TEXT_RESET
    read -p "       Wanna Reboot now? [y/n] " INT_REBOOT
    if [[ $INT_REBOOT == y  ]]
    then
        sudo reboot
    else
        echo "	Aborting reboot... "
    fi;
fi;



exit
